<a href="https://colab.research.google.com/github/sirakik/japan_graph/blob/master/%E3%82%B3%E3%83%AD%E3%83%8A%E3%83%87%E3%83%BC%E3%82%BF%E8%A6%96%E5%AF%9F.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#下ごしらえ

In [26]:
import csv
import datetime
import numpy as np

In [6]:
!wget -q https://raw.githubusercontent.com/kaz-ogiwara/covid19/master/data/prefectures.csv -O corona.csv

# データ読み込み

testedPositive: 検査陽性者数  
peopleTested: 検査実施人数  
hospitalized: 入院治療等を要する者  
serious: 重症者数  
discharged: 退院・療養解除  
deaths: 死亡者数  
effectiveReproductionNumber: 実効再生産数

In [65]:
dt1 = datetime.datetime(year=2020, month=2, day=8) #　2月8日からデータが始まっています
dt2 = datetime.datetime(year=2020, month=9, day=13) # ほぼ毎日更新っぽいので，今日の日付に合わせましょう．ただし何時更新かは知らないので，手作業で合わせてください
dif_days = (dt2 - dt1).days +1
print('#　日数: ', dif_days)

#　日数:  219


In [47]:
# 都道府県名 (データに合わせて, GummaをGunmaに変更)
todofuken = {0:'Hokkaido', 1:'Aomori', 2:'Iwate', 3:'Miyagi', 4:'Akita', 5:'Yamagata', 6:'Fukushima', 7:'Ibaraki', 8:'Tochigi', 9:'Gunma', 10:'Saitama', 11:'Chiba', 12:'Tokyo', 13:'Kanagawa', 14:'Niigata', 15:'Toyama', 16:'Ishikawa', 17:'Fukui', 18:'Yamanashi', 19:'Nagano', 20:'Gifu', 21:'Shizuoka', 22:'Aichi', 23:'Mie', 24:'Shiga', 25:'Kyoto', 26:'Osaka', 27:'Hyogo', 28:'Nara', 29:'Wakayama', 30:'Tottori', 31:'Shimane', 32:'Okayama', 33:'Hiroshima', 34:'Yamaguchi', 35:'Tokushima', 36:'Kagawa', 37:'Ehime', 38:'Kochi', 39:'Fukuoka', 40:'Saga', 41:'Nagasaki', 42:'Kumamoto', 43:'Oita', 44:'Miyazaki', 45:'Kagoshima', 46:'Okinawa'}

def find_key(value):
    for k, v in todofuken.items():
        if value == v:
          return k

In [67]:
daily_infected = np.zeros((47, dif_days))

with open('corona.csv') as f:
    corona_data = csv.reader(f)
    for i, d in enumerate(corona_data):
        if i == 0:
            continue

        # 都道府県番号を取得
        key = find_key(d[4])
        
        # 日付を配列番号に変更
        dt = datetime.datetime(year=int(d[0]), month=int(d[1]), day=int(d[2]))
        index = (dt - dt1).days
        daily_infected[key][index] = float(d[5])

print(daily_infected)

[[   0.    0.    0. ... 1860. 1866. 1873.]
 [   0.    0.    0. ...   35.   35.   35.]
 [   0.    0.    0. ...   23.   23.   23.]
 ...
 [   0.    0.    0. ...  339.  340.  342.]
 [   0.    0.    0. ...  372.  372.  372.]
 [   0.    0.    0. ... 2269. 2280. 2290.]]
